apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: large-payload-vs
  namespace: default
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: default-httpbin-8000
            namespace: gloo-system
      options:
        stagedTransformations:
          early:
            requestTransforms:
              - matcher:
                  prefix: /
                requestTransformation:
                  transformationTemplate:
                    passthrough: {}
                    headers:
                      x-my-custom-header:
                        text: 'my-custom-value'