apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: jwt-opa
  namespace: gloo-system
spec:
  configs:
  - opaAuth:
      modules:
      - name: opa-policy
        namespace: gloo-system
      query: "data.test.deny == false"
